const AUTHENTICATE_ROUTE = {
    LOGIN: '@AUTHENTICATE_ROUTE/LOGIN',
};

const APP_ROUTE = {
    HOME: 'HOME',
    MAIN_TAB: 'MAIN_TAB',
};

const HOME_ROUTE = {
    ROOT: 'HOME_ROOT',
    HOME: 'HOME',
    HOME_DETAIL: 'HOME_DETAIL',
    WEB_VIEW: 'WEB_VIEW',
};

const SETTING_ROUTE = {
    ROOT: 'SETTING_ROOT',
};

const NOTIFICATION_ROUTE = {
    ROOT: 'NOTIFICATION_ROOT',
};

const TAB_NAVIGATION_ROOT = {
    HOME_ROUTE,
    SETTING_ROUTE,
    NOTIFICATION_ROUTE,
};

export { APP_ROUTE, TAB_NAVIGATION_ROOT, AUTHENTICATE_ROUTE };
